title: JGr in VR
description: Docs for the GR in VR project
theme: just-the-docs

url: https://raichkel.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
